api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "bouquet-cart-transform"
type = "function"
uid = "47a65174-d7fa-b1bf-de2c-28aa4e47392126a059a1"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart_transform_run"

  [extensions.build]
  command = "cargo build --target=wasm32-unknown-unknown --release"
  path = "target/wasm32-unknown-unknown/release/bouquet-cart-transform.wasm"
  watch = [ "src/**/*.rs" ]

  [extensions.ui.paths]
  create = "/"
  details = "/"
